### ISSUE TITLE
webhook config should prevent deadlock

### ISSUE THREAD

**Issue by jefimm** [doitintl/gtoken#15]
Please see https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector
At least kube-system ns should be excluded

**Comment by jefimm** [comment]
see https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-deadlocks-in-self-hosted-webhooks

**Comment by alexei-led** [comment]
solved with PR #16
